# Change the title, it's for you. Maybe you see "My newspaper"?
title: "Hacker's Den"

# Options: light, dark, sepia or clojure 
theme: dark

# Options: daily, weekly or all
edition: all

feeds:
  - https://notifycyber.com/rss?sources=caisa%2Cisg%2Cthn%2Cdr%2Ccve
  - https://kill-the-newsletter.com/feeds/oozrzxtg7nxieettty99.xml
