# Change the title, it's for you. Maybe you see "My newspaper"?
title: "Hacker's Den"

# Options: light, dark, sepia or clojure 
theme: dark

# Options: daily, weekly or all
edition: all

feeds:
  - https://cy83r-3x71nc710n.github.io/feed.xml
