# Change the title, it's for you. Maybe you see "My newspaper"?
title: "Hacker's Den"

# Options: light, dark, sepia or clojure 
theme: dark

# Options: daily, weekly or all
edition: daily

feeds:
  - https://programadorwebvalencia.com/feed/
  - https://republicaweb.es/feed/
  - https://www.360quadrants.com/blog/feed/
