name: update newspaper
on:
  schedule:
    - cron: "0 0 * * *"
  push:
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove existing
        run: rm -rf ./dist
      - name: Update newspaper
        run: java -jar ./rsspaper-1.2.4-standalone.jar
      - name: move files for overwrite & update index.html with changes
        run: | 
          mv -f ./manifest.json ./dist/static/manifest.json && mv -f ./newsreader-not-cover.png ./dist/static/img/newsreader-not-cover.png
          sed -i 's|href="https://github.com/tanrax/RSSpaper">RSSpaper<\/a> and a lot of <span class="footer__heard">❤️<\/span>️|href="https://github.com/CY83R-3X71NC710N/Hackers-Den">Hackers-Den By CY83R-3X71NC710N<\/a>|; s|<meta name="description" content="My static news generator">|<meta name="description" content="Hackers-Den Publishing">|' ./dist/index.html
      - name: Push
        run: |
          git config --global user.name CY83R-3X71NC710N
          git config --global user.email $EMAIL
          git add **
          git commit -m 'Build'
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      EMAIL: ${{ secrets.EMAIL }}
